-- RESET COMPLETO DO BANCO DE DADOS - KEEPGOING ERP
-- Este script cria todas as tabelas do zero com suporte a Multi-Tenancy (company_id)

-- 0. TABELA DE EMPRESAS (Necessária para referências)
CREATE TABLE IF NOT EXISTS companies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    document TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Inserir empresa padrão para evitar erros de FK se necessário (UUID Zero)
INSERT INTO companies (id, name) VALUES ('00000000-0000-0000-0000-000000000000', 'Empresa Padrão') ON CONFLICT (id) DO NOTHING;

-- 1. TABELAS DE APOIO
CREATE TABLE IF NOT EXISTS suppliers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    type TEXT,
    document TEXT,
    legal_name TEXT,
    trading_name TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    cellphone TEXT,
    website TEXT,
    address JSONB,
    observations TEXT,
    supplier_code INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS architects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    type TEXT,
    document TEXT,
    legal_name TEXT,
    trading_name TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    cellphone TEXT,
    address JSONB,
    observations TEXT,
    architect_code INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS brands (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    name TEXT NOT NULL, -- Campo obrigatório para o backend
    type TEXT,
    document TEXT,
    rg_insc TEXT,
    legal_name TEXT,
    trading_name TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    cellphone TEXT,
    address JSONB,
    client_code INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. MATÉRIA PRIMA
CREATE TABLE IF NOT EXISTS materials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'Matéria Prima',
    status TEXT DEFAULT 'ativo',
    unit_cost DECIMAL(12,2) DEFAULT 0,
    unit TEXT,
    min_stock DECIMAL(12,2) DEFAULT 0,
    max_stock DECIMAL(12,2) DEFAULT 0,
    stock_quantity DECIMAL(12,2) DEFAULT 0,
    registration_date DATE DEFAULT CURRENT_DATE,
    brand TEXT,
    supplier_id UUID REFERENCES suppliers(id),
    category TEXT,
    difal DECIMAL(5,2) DEFAULT 0,
    freight_cost DECIMAL(12,2) DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    loss_percentage DECIMAL(5,2) DEFAULT 0,
    profit_margin DECIMAL(5,2) DEFAULT 0,
    commission_percentage DECIMAL(5,2) DEFAULT 0,
    discount_percentage DECIMAL(5,2) DEFAULT 0,
    suggested_price DECIMAL(12,2) DEFAULT 0,
    selling_price DECIMAL(12,2) DEFAULT 0,
    currency TEXT DEFAULT 'BRL',
    dolar_rate DECIMAL(10,4) DEFAULT 0,
    euro_rate DECIMAL(10,4) DEFAULT 0,
    bcfp DECIMAL(12,2) DEFAULT 0,
    thickness DECIMAL(5,2),
    weight DECIMAL(10,2),
    m2_per_unit DECIMAL(10,2),
    inventory_location TEXT,
    price_history JSONB DEFAULT '[]'::jsonb,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. PRODUTOS E SERVIÇOS
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    name TEXT NOT NULL,
    category TEXT,
    status TEXT DEFAULT 'ativo',
    base_price DECIMAL(12,2) DEFAULT 0,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. VENDAS E ORÇAMENTOS
CREATE TABLE IF NOT EXISTS sales (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    order_number TEXT NOT NULL,
    client_name TEXT NOT NULL,
    client_document TEXT,
    client_phone TEXT,
    client_email TEXT,
    status TEXT DEFAULT 'budget',
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    subtotal DECIMAL(12,2) DEFAULT 0,
    discount DECIMAL(12,2) DEFAULT 0,
    total DECIMAL(12,2) DEFAULT 0,
    order_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    delivery_date DATE,
    shipping_address JSONB,
    billing_address JSONB,
    payment_method TEXT,
    payment_status TEXT,
    seller_name TEXT,
    notes TEXT,
    is_os_generated BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS orders_service (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    os_number TEXT NOT NULL,
    order_number TEXT,
    client_name TEXT NOT NULL,
    project_description TEXT,
    material TEXT,
    material_area DECIMAL(10,2),
    phase TEXT NOT NULL,
    seller TEXT,
    deadline DATE,
    priority TEXT DEFAULT 'media',
    client_id UUID REFERENCES clients(id),
    architect_id UUID REFERENCES architects(id),
    architect_name TEXT,
    total_value DECIMAL(12,2),
    remaining_value DECIMAL(12,2),
    observations TEXT,
    internal_observations TEXT,
    image_urls JSONB DEFAULT '[]'::jsonb,
    items JSONB DEFAULT '[]'::jsonb,
    payments JSONB DEFAULT '[]'::jsonb,
    logs JSONB DEFAULT '[]'::jsonb,
    phase_history JSONB DEFAULT '[]'::jsonb,
    responsible_staff_name TEXT,
    sales_channel TEXT,
    sales_phase TEXT,
    is_os_generated BOOLEAN DEFAULT true,
    status TEXT,
    discount_value DECIMAL(12,2),
    discount_percentage DECIMAL(5,2),
    payment_conditions TEXT,
    delivery_deadline TEXT,
    totals JSONB DEFAULT '{}'::jsonb,
    lost_reason TEXT,
    lost_details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. AUDITORIA E ENTREGAS
CREATE TABLE IF NOT EXISTS activity_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    type TEXT,
    message TEXT,
    reference_id TEXT,
    user_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    company_id UUID REFERENCES companies(id),
    order_id TEXT,
    os_number TEXT,
    client_name TEXT NOT NULL,
    address TEXT NOT NULL,
    date DATE,
    time TEXT,
    status TEXT DEFAULT 'agendado',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 6. SEGURANÇA (RLS)
-- Define políticas abertas iniciais para garantir que a persistência funcione imediatamente
DO $$ 
DECLARE
    t text;
BEGIN 
    FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_owner = 'postgres'
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS "Public Access" ON %I', t);
        EXECUTE format('CREATE POLICY "Public Access" ON %I FOR ALL USING (true) WITH CHECK (true)', t);
    END LOOP;
END $$;
