-- Carga em massa de Matéria Prima (Aglostone) conforme planilha fornecida
-- Para executar: Copie e cole este script no SQL Editor do Supabase

INSERT INTO materials (
    code,
    name,
    brand,
    category,
    type,
    thickness,
    unit_cost,
    freight_cost,
    loss_percentage,
    tax_percentage,
    profit_margin,
    commission_percentage,
    discount_percentage,
    suggested_price,
    selling_price,
    unit,
    status,
    currency,
    dolar_rate,
    euro_rate,
    stock_quantity,
    min_stock
) VALUES 
(
    '28', 
    'AGL. BEGE PRIME AGLOSTONE', 
    'AGLOSTONE', 
    'Matéria Prima', 
    'Matéria Prima', 
    2.0, 
    250.00, 
    0.00, 
    20.00, 
    6.00, 
    46.50, 
    2.50, 
    5.00, 
    750.00, 
    750.00, 
    'M2', 
    'ativo',
    'BRL',
    1.0,
    1.0,
    0,
    0
),
(
    '29', 
    'AGL. BRANCO PRIME AGLOSTONE', 
    'AGLOSTONE', 
    'Matéria Prima', 
    'Matéria Prima', 
    1.6, 
    228.00, 
    0.00, 
    20.00, 
    6.00, 
    54.31, 
    2.50, 
    5.00, 
    850.00, 
    850.00, 
    'M2', 
    'ativo',
    'BRL',
    1.0,
    1.0,
    0,
    0
)
ON CONFLICT (code) 
DO UPDATE SET
    name = EXCLUDED.name,
    brand = EXCLUDED.brand,
    thickness = EXCLUDED.thickness,
    unit_cost = EXCLUDED.unit_cost,
    freight_cost = EXCLUDED.freight_cost,
    loss_percentage = EXCLUDED.loss_percentage,
    tax_percentage = EXCLUDED.tax_percentage,
    profit_margin = EXCLUDED.profit_margin,
    commission_percentage = EXCLUDED.commission_percentage,
    discount_percentage = EXCLUDED.discount_percentage,
    suggested_price = EXCLUDED.suggested_price,
    selling_price = EXCLUDED.selling_price;
