-- SCRIPT DE MIGRAÇÃO: CÓDIGOS SEQUENCIAIS PARA FORNECEDORES E ARQUITETOS
-- Execute este script no SQL Editor do Supabase

-- 1. ADICIONAR CÓDIGO SEQUENCIAL PARA FORNECEDORES
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='suppliers' AND column_name='supplier_code') THEN
        ALTER TABLE suppliers ADD COLUMN supplier_code INT GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- 2. CRIAR TABELA DE ARQUITETOS (CASO NÃO EXISTA) E ADICIONAR CÓDIGO
CREATE TABLE IF NOT EXISTS architects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT,
    document TEXT,
    legal_name TEXT,
    trading_name TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    cellphone TEXT,
    address JSONB,
    observations TEXT,
    architect_code INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Ativar RLS para arquitetos (Segurança)
ALTER TABLE architects ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'architects' AND policyname = 'Public Access') THEN
        CREATE POLICY "Public Access" ON architects FOR ALL USING (true);
    END IF;
END $$;
