-- SCRIPT DE CRIAÇÃO DO BANCO DE DADOS - MARMOFLOW ERP
-- Execute este script no SQL Editor do seu projeto no Supabase

-- 1. TABELAS DE APOIO
CREATE TABLE IF NOT EXISTS suppliers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT,
    document TEXT,
    legal_name TEXT,
    trading_name TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    website TEXT,
    address JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS brands (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS clients (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    type TEXT,
    document TEXT,
    rg_insc TEXT,
    legal_name TEXT,
    trading_name TEXT,
    contact_name TEXT,
    email TEXT,
    phone TEXT,
    cellphone TEXT,
    address JSONB,
    client_code INT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);


-- 2. MATÉRIA PRIMA
CREATE TABLE IF NOT EXISTS materials (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'Matéria Prima',
    status TEXT DEFAULT 'ativo',
    unit_cost DECIMAL(12,2) DEFAULT 0,
    unit TEXT,
    min_stock DECIMAL(12,2) DEFAULT 0,
    max_stock DECIMAL(12,2) DEFAULT 0,
    stock_quantity DECIMAL(12,2) DEFAULT 0,
    registration_date DATE DEFAULT CURRENT_DATE,
    brand TEXT,
    supplier_id UUID REFERENCES suppliers(id),
    category TEXT,
    
    -- Campos de Precificação
    difal DECIMAL(5,2) DEFAULT 0,
    freight_cost DECIMAL(12,2) DEFAULT 0,
    tax_percentage DECIMAL(5,2) DEFAULT 0,
    loss_percentage DECIMAL(5,2) DEFAULT 0,
    profit_margin DECIMAL(5,2) DEFAULT 0,
    commission_percentage DECIMAL(5,2) DEFAULT 0,
    discount_percentage DECIMAL(5,2) DEFAULT 0,
    suggested_price DECIMAL(12,2) DEFAULT 0,
    selling_price DECIMAL(12,2) DEFAULT 0,
    currency TEXT DEFAULT 'BRL',
    dolar_rate DECIMAL(10,4) DEFAULT 0,
    euro_rate DECIMAL(10,4) DEFAULT 0,
    bcfp DECIMAL(12,2) DEFAULT 0,
    
    -- Campos de Chapa
    thickness DECIMAL(5,2),
    weight DECIMAL(10,2),
    m2_per_unit DECIMAL(10,2),
    inventory_location TEXT,
    
    -- Histórico e Metadados
    price_history JSONB DEFAULT '[]'::jsonb,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 3. PRODUTOS E SERVIÇOS
CREATE TABLE IF NOT EXISTS products (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    category TEXT,
    status TEXT DEFAULT 'ativo',
    base_price DECIMAL(12,2) DEFAULT 0,
    description TEXT,
    image_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. VENDAS E ORÇAMENTOS
CREATE TABLE IF NOT EXISTS sales (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_number TEXT UNIQUE NOT NULL,
    client_name TEXT NOT NULL,
    client_document TEXT,
    client_phone TEXT,
    client_email TEXT,
    status TEXT DEFAULT 'budget', -- 'budget', 'order', 'canceled'
    items JSONB NOT NULL DEFAULT '[]'::jsonb,
    subtotal DECIMAL(12,2) DEFAULT 0,
    discount DECIMAL(12,2) DEFAULT 0,
    total DECIMAL(12,2) DEFAULT 0,
    order_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    delivery_date DATE,
    shipping_address JSONB,
    billing_address JSONB,
    payment_method TEXT,
    payment_status TEXT,
    seller_name TEXT,
    notes TEXT,
    is_os_generated BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS orders_service (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    os_number TEXT UNIQUE NOT NULL,
    order_number TEXT,
    client_name TEXT NOT NULL,
    project_description TEXT,
    material TEXT,
    material_area DECIMAL(10,2),
    phase TEXT NOT NULL,
    seller TEXT,
    deadline DATE,
    priority TEXT DEFAULT 'media',
    client_id UUID,
    architect_id UUID,
    architect_name TEXT,
    total_value DECIMAL(12,2),
    remaining_value DECIMAL(12,2),
    observations TEXT,
    internal_observations TEXT,
    image_urls JSONB DEFAULT '[]'::jsonb,
    items JSONB DEFAULT '[]'::jsonb,
    payments JSONB DEFAULT '[]'::jsonb,
    logs JSONB DEFAULT '[]'::jsonb,
    phase_history JSONB DEFAULT '[]'::jsonb,
    responsible_staff_name TEXT,
    sales_channel TEXT,
    sales_phase TEXT,
    is_os_generated BOOLEAN DEFAULT true,
    status TEXT,
    discount_value DECIMAL(12,2),
    discount_percentage DECIMAL(5,2),
    payment_conditions TEXT,
    delivery_deadline TEXT,
    totals JSONB DEFAULT '{}'::jsonb,
    lost_reason TEXT,
    lost_details TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. AUDITORIA / LOGS
CREATE TABLE IF NOT EXISTS activity_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    type TEXT,
    message TEXT,
    reference_id TEXT,
    user_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS deliveries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id TEXT,
    os_number TEXT,
    client_name TEXT NOT NULL,
    address TEXT NOT NULL,
    date DATE,
    time TEXT,
    status TEXT DEFAULT 'agendado',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Ativar RLS (Segurança) básico
ALTER TABLE materials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON materials FOR ALL USING (true);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON products FOR ALL USING (true);

ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON sales FOR ALL USING (true);

ALTER TABLE clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON clients FOR ALL USING (true);

ALTER TABLE orders_service ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON orders_service FOR ALL USING (true);

ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON activity_logs FOR ALL USING (true);

ALTER TABLE deliveries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access" ON deliveries FOR ALL USING (true);
